export const seedCategories = [
  { id: "cat-new-taipei-urban", title: "新北市都市更新", sortOrder: 1 },
  { id: "cat-taipei-planning", title: "台北市都市計畫", sortOrder: 2 },
  { id: "cat-regional", title: "區域與政策規劃", sortOrder: 3 },
  { id: "cat-research", title: "規劃研究專案", sortOrder: 4 },
  { id: "cat-miaoli", title: "苗栗縣都市計畫", sortOrder: 5 },
];

export const seedProjects = [
  {
    id: "wugu",
    categoryId: "cat-new-taipei-urban",
    title: "新北市五股區審議大會通過",
    description:
      "賀擬訂新北市五股區中興段777地號(原更寮段褒子寮小段73-4地號)等9筆(原5筆)土地都市更新事業計畫案 審議大會通過",
    image: "/assets/projectInHome1.jpg",
    client: "新北市政府",
    siteLocation: "新北市五股區",
    siteArea: "—",
    features: "都市更新事業計畫案",
    status: "審議通過",
    isFeatured: true,
    sortOrder: 1,
  },
  {
    id: "zhonghe",
    categoryId: "cat-new-taipei-urban",
    title: "新北市中和區審議大會通過",
    description:
      "賀擬訂新北市中和區健康段954地號等7筆土地都市更新事業計畫案 審議大會通過",
    image: "/assets/projectInHome2.jpg",
    client: "新北市政府",
    siteLocation: "新北市中和區",
    siteArea: "—",
    features: "都市更新事業計畫案",
    status: "審議通過",
    isFeatured: true,
    sortOrder: 2,
  },
  {
    id: "wugu-plan",
    categoryId: "cat-new-taipei-urban",
    title: "五股區中興段都市更新事業計畫案",
    description: "五股區中興段都市更新事業計畫編撰與審議協助。",
    image: "/assets/projectInHome1.jpg",
    client: "地主聯合籌備組",
    siteLocation: "新北市五股區中興段",
    siteArea: "—",
    features: "事業計畫編撰",
    status: "執行中",
    isFeatured: false,
    sortOrder: 3,
  },
  {
    id: "zhonghe-plan",
    categoryId: "cat-new-taipei-urban",
    title: "中和區健康段都市更新事業計畫案",
    description: "中和區健康段都市更新事業計畫編撰與審議協助。",
    image: "/assets/projectInHome2.jpg",
    client: "地主聯合籌備組",
    siteLocation: "新北市中和區健康段",
    siteArea: "—",
    features: "事業計畫編撰",
    status: "執行中",
    isFeatured: false,
    sortOrder: 4,
  },
  {
    id: "banqiao-eval",
    categoryId: "cat-new-taipei-urban",
    title: "板橋區○○段都市更新評估案",
    description: "都市更新可行性評估與權利變換試算。",
    image: "",
    client: "—",
    siteLocation: "新北市板橋區",
    siteArea: "—",
    features: "可行性評估",
    status: "評估中",
    isFeatured: false,
    sortOrder: 5,
  },
  {
    id: "sanchong-plan",
    categoryId: "cat-new-taipei-urban",
    title: "三重區○○段事業計畫編撰案",
    description: "三重區都市更新事業計畫編撰。",
    image: "",
    client: "—",
    siteLocation: "新北市三重區",
    siteArea: "—",
    features: "事業計畫編撰",
    status: "規劃中",
    isFeatured: false,
    sortOrder: 6,
  },
  {
    id: "xinyi-zoning",
    categoryId: "cat-taipei-planning",
    title: "信義區土地使用分區變更案",
    description: "土地使用分區變更規劃與審議文件編製。",
    image: "",
    client: "—",
    siteLocation: "台北市信義區",
    siteArea: "—",
    features: "分區變更",
    status: "執行中",
    isFeatured: false,
    sortOrder: 1,
  },
  {
    id: "neihu-detail",
    categoryId: "cat-taipei-planning",
    title: "內湖區細部計畫檢討案",
    description: "細部計畫通盤檢討與圖說編製。",
    image: "",
    client: "—",
    siteLocation: "台北市內湖區",
    siteArea: "—",
    features: "細部計畫檢討",
    status: "執行中",
    isFeatured: false,
    sortOrder: 2,
  },
  {
    id: "shilin-permit",
    categoryId: "cat-taipei-planning",
    title: "士林區○○段開發許可輔導案",
    description: "開發許可申請輔導與文件整合。",
    image: "",
    client: "—",
    siteLocation: "台北市士林區",
    siteArea: "—",
    features: "開發許可輔導",
    status: "規劃中",
    isFeatured: false,
    sortOrder: 3,
  },
  {
    id: "beitou-research",
    categoryId: "cat-taipei-planning",
    title: "北投區○○段規劃研究案",
    description: "土地使用與開發潛力規劃研究。",
    image: "",
    client: "—",
    siteLocation: "台北市北投區",
    siteArea: "—",
    features: "規劃研究",
    status: "評估中",
    isFeatured: false,
    sortOrder: 4,
  },
  {
    id: "county-regional",
    categoryId: "cat-regional",
    title: "○○縣區域計畫修訂案",
    description: "區域計畫修訂與政策分析。",
    image: "",
    client: "—",
    siteLocation: "—",
    siteArea: "—",
    features: "區域計畫修訂",
    status: "規劃中",
    isFeatured: false,
    sortOrder: 1,
  },
  {
    id: "industrial-strategy",
    categoryId: "cat-regional",
    title: "○○市產業園區發展策略研究",
    description: "產業園區發展策略與空間配置研究。",
    image: "",
    client: "—",
    siteLocation: "—",
    siteArea: "—",
    features: "政策研究",
    status: "評估中",
    isFeatured: false,
    sortOrder: 2,
  },
  {
    id: "transit-land",
    categoryId: "cat-regional",
    title: "交通節點周邊土地使用檢討",
    description: "交通導向開發與土地使用檢討。",
    image: "",
    client: "—",
    siteLocation: "—",
    siteArea: "—",
    features: "TOD 檢討",
    status: "執行中",
    isFeatured: false,
    sortOrder: 3,
  },
  {
    id: "public-facility",
    categoryId: "cat-regional",
    title: "公共設施用地配置分析",
    description: "公共設施用地需求與配置分析。",
    image: "",
    client: "—",
    siteLocation: "—",
    siteArea: "—",
    features: "公共設施分析",
    status: "規劃中",
    isFeatured: false,
    sortOrder: 4,
  },
  {
    id: "social-housing",
    categoryId: "cat-research",
    title: "社會住宅選址可行性研究",
    description: "社會住宅選址與可行性評估。",
    image: "",
    client: "—",
    siteLocation: "—",
    siteArea: "—",
    features: "可行性研究",
    status: "評估中",
    isFeatured: false,
    sortOrder: 1,
  },
  {
    id: "tod-potential",
    categoryId: "cat-research",
    title: "TOD 導向開發潛力評估",
    description: "大眾運輸導向開發潛力評估。",
    image: "",
    client: "—",
    siteLocation: "—",
    siteArea: "—",
    features: "TOD 評估",
    status: "評估中",
    isFeatured: false,
    sortOrder: 2,
  },
  {
    id: "urban-design",
    categoryId: "cat-research",
    title: "都市設計與景觀視覺分析",
    description: "都市設計與景觀視覺影響分析。",
    image: "",
    client: "—",
    siteLocation: "—",
    siteArea: "—",
    features: "景觀分析",
    status: "執行中",
    isFeatured: false,
    sortOrder: 3,
  },
  {
    id: "eco-review",
    categoryId: "cat-research",
    title: "環境影響與生態檢討輔助",
    description: "環境影響與生態檢討輔助分析。",
    image: "",
    client: "—",
    siteLocation: "—",
    siteArea: "—",
    features: "生態檢討",
    status: "規劃中",
    isFeatured: false,
    sortOrder: 4,
  },
  {
    id: "miaoli-county-plan",
    categoryId: "cat-miaoli",
    title: "苗栗縣都市計畫通盤檢討案",
    description: "苗栗縣都市計畫通盤檢討與圖資建置。",
    image: "/assets/projectsBanner.jpg",
    client: "苗栗縣政府",
    siteLocation: "全苗栗縣",
    siteArea: "182,031.49公頃",
    features: "建置中",
    status: "建置中",
    isFeatured: false,
    sortOrder: 1,
  },
];

export function getSeedData() {
  return {
    categories: seedCategories.map((c) => ({ ...c })),
    projects: seedProjects.map((p) => ({ ...p })),
  };
}
